pipeline:
  build_linux_amd64:
    image: golang:1.9
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/hello
      - tar -cvzf hello-linux-amd64.tar.gz -C release/linux/amd64/ .
  build_linux_arm64:
    image: golang:1.9
    group: build
    environment:
      - GOOS=darwin
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/darwin/amd64/hello
      - tar -cvzf hello-darwin-amd64.tar.gz -C release/darwin/amd64/ .
  publish_github:
    image: plugins/github-release
    secrets: [ github_token ]
    files: ./*.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
    when:
      event: tag
